# Generated by Django 5.2.7 on 2025-11-09 17:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '個人資料', 'verbose_name_plural': '個人資料'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': '角色', 'verbose_name_plural': '角色'},
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 9, 17, 12, 59, 58670, tzinfo=datetime.timezone.utc), verbose_name='建立時間'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='科系'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='電子郵件'),
        ),
        migrations.AddField(
            model_name='profile',
            name='grade',
            field=models.IntegerField(blank=True, null=True, verbose_name='年級'),
        ),
        migrations.AddField(
            model_name='profile',
            name='office',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='研究室'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='電話'),
        ),
        migrations.AddField(
            model_name='profile',
            name='real_name',
            field=models.CharField(default='未設定姓名', max_length=50, verbose_name='姓名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='學號'),
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='職稱'),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='roles',
            field=models.ManyToManyField(to='accounts.role', verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('student', '學生'), ('teacher', '教師'), ('admin', '管理員')], max_length=20, unique=True, verbose_name='角色名稱'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, unique=True, verbose_name='課程代碼')),
                ('course_name', models.CharField(max_length=100, verbose_name='課程名稱')),
                ('course_type', models.CharField(choices=[('required', '必修'), ('elective', '選修'), ('general', '通識')], max_length=10, verbose_name='課程類別')),
                ('description', models.TextField(blank=True, verbose_name='課程描述')),
                ('credits', models.IntegerField(verbose_name='學分數')),
                ('hours', models.IntegerField(verbose_name='課程節數')),
                ('academic_year', models.CharField(max_length=10, verbose_name='學年度')),
                ('semester', models.CharField(choices=[('1', '上學期'), ('2', '下學期')], max_length=1, verbose_name='學期')),
                ('department', models.CharField(max_length=100, verbose_name='開課系所')),
                ('grade_level', models.IntegerField(verbose_name='建議修課年級')),
                ('classroom', models.CharField(max_length=50, verbose_name='課程教室')),
                ('weekday', models.CharField(choices=[('1', '星期一'), ('2', '星期二'), ('3', '星期三'), ('4', '星期四'), ('5', '星期五'), ('6', '星期六'), ('7', '星期日')], max_length=1, verbose_name='星期幾')),
                ('start_period', models.IntegerField(verbose_name='開始節次')),
                ('end_period', models.IntegerField(verbose_name='結束節次')),
                ('max_students', models.IntegerField(default=50, verbose_name='人數上限')),
                ('current_students', models.IntegerField(default=0, verbose_name='目前人數')),
                ('status', models.CharField(choices=[('open', '開放選課'), ('full', '已額滿'), ('closed', '停開')], default='open', max_length=10, verbose_name='開課狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_courses', to=settings.AUTH_USER_MODEL, verbose_name='授課教師')),
            ],
            options={
                'verbose_name': '課程',
                'verbose_name_plural': '課程',
                'ordering': ['course_code'],
            },
        ),
        migrations.CreateModel(
            name='CreditSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_credits', models.IntegerField(default=0, verbose_name='總學分')),
                ('required_credits', models.IntegerField(default=0, verbose_name='必修學分')),
                ('elective_credits', models.IntegerField(default=0, verbose_name='選修學分')),
                ('general_credits', models.IntegerField(default=0, verbose_name='通識學分')),
                ('passed_credits', models.IntegerField(default=0, verbose_name='已通過學分')),
                ('failed_credits', models.IntegerField(default=0, verbose_name='未通過學分')),
                ('gpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='學期平均 GPA')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_summary', to=settings.AUTH_USER_MODEL, verbose_name='學生')),
            ],
            options={
                'verbose_name': '學分統計',
                'verbose_name_plural': '學分統計',
            },
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=10, verbose_name='學年度')),
                ('semester', models.CharField(max_length=10, verbose_name='學期')),
                ('status', models.CharField(choices=[('enrolled', '已選課'), ('passed', '已通過'), ('failed', '未通過'), ('dropped', '已退選')], default='enrolled', max_length=10, verbose_name='狀態')),
                ('grade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D', 'D'), ('F', 'F')], max_length=3, null=True, verbose_name='等第成績')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='百分制成績')),
                ('enrolled_date', models.DateTimeField(auto_now_add=True, verbose_name='選課日期')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='accounts.course', verbose_name='課程')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL, verbose_name='學生')),
            ],
            options={
                'verbose_name': '學生選課記錄',
                'verbose_name_plural': '學生選課記錄',
                'ordering': ['-academic_year', '-semester'],
                'unique_together': {('student', 'course', 'academic_year', 'semester')},
            },
        ),
    ]
